# vim: ft=zsh sw=2 ts=2 et
#
# Executes commands at login pre-zshrc.
# Loaded only for login shells, _before_ zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Matt Black <dev@mafro.net>
#

#
# Browser
#

if [[ -z "$BROWSER" && "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

if [[ -z "$EDITOR" ]]; then
  export EDITOR='vim'
fi
if [[ -z "$VISUAL" ]]; then
  export EDITOR='vim'
fi
if [[ -z "$PAGER" ]]; then
  export PAGER='less'
fi

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_GB.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  $HOME/{,s}bin(N)
  /opt/{homebrew,local}/{,s}bin(N)
  /usr/local/{,s}bin(N)
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X to enable it.
if [[ -z "$LESS" ]]; then
  export LESS='-g -i -M -R -S -w -X -z-4'
fi

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if [[ -z "$LESSOPEN" ]] && (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Editor and colour
#
export EDITOR=vim
export VISUAL=vim
export TERM=xterm-256color

# mafrosis/dotfiles/zsh/bat/mafro.tmTheme
export BAT_THEME=mafro
# Pretty manpages (bat)
export MANPAGER="sh -c 'col -bx | bat -l man -p'"

#
# Homebrew
#
if command -v brew >/dev/null 2>&1; then
  eval $(brew shellenv)
  export HOMEBREW_NO_ENV_HINTS=1
  export HOMEBREW_NO_INSTALL_CLEANUP=1

  # include Homebrew completions
  # add to fpath before prezto calls compinit
  export FPATH=${HOMEBREW_PREFIX}/share/zsh/site-functions:${FPATH}
fi

#
# Golang
#
export GOPATH=${HOME}/Development/go
export PATH=${PATH}:${GOPATH}/bin:/usr/local/opt/go/libexec/bin

#
# Python and virtualenv
#
# no virtualenv prompt; shown via prezto theme
export VIRTUAL_ENV_DISABLE_PROMPT=1

#
# AWS and GCP
#
export AWS_DEFAULT_REGION=ap-southeast-2

if [[ -v HOMEBREW_PREFIX ]]; then
  source ${HOMEBREW_PREFIX}/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc
  source ${HOMEBREW_PREFIX}/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc
fi
